### ISSUE TITLE
Greetings! This beautiful addon does not work in new versions of nvda_2024

### ISSUE THREAD

**Issue by Lo-lo78** [huaiyinfeilong/audiomanager#1]
Hi, I use this addon a lot and I'm happy with it.
With the 2024 beta versions it is no longer possible to use the addon.
Thanks for everything you do!

**Comment by huaiyinfeilong** [comment]
Hi,

 

We will adapt to the official version in the future. Thank you!

 

发件人: ***@***.*** ***@***.***> 代表 Lo-lo78
发送时间: 2024年1月26日 23:43
收件人: huaiyinfeilong/audiomanager ***@***.***>
抄送: Subscribed ***@***.***>
主题: [huaiyinfeilong/audiomanager] Greetings! This beautiful addon does not work in new versions of nvda_2024 (Issue #1)

 

Hi, I use this addon a lot and I'm happy with it.
With the 2024 beta versions it is no longer possible to use the addon.
Thanks for everything you do!
